# kian主题配置

favicon: https://0.gravatar.com/avatar/3bf90e6ff51b554212120c7be4fdfd302f2a26ef1ff6aa74cf4d5595033627c6
# 头像
avatar: https://0.gravatar.com/avatar/3bf90e6ff51b554212120c7be4fdfd302f2a26ef1ff6aa74cf4d5595033627c6?size=50

# 菜单
menu:
  归档: /archives
  关于: /about

# giscus 评论系统
# https://giscus.app/
giscus:
  enable: true
  repo: kianfang/kianfang
  repo_id: R_kgDOJXzVaA
  category: Comments
  category_id: DIC_kwDOJXzVaM4CW0EL
